In [6]:
from datetime import datetime
import pandas as pd
import time
import re
import os
import openpyxl

start=datetime.strptime("201601","%Y%m")
end=datetime.strptime("202010","%Y%m")
dates=[date.strftime("%Y%m") for date in pd.date_range(start=start,end=end,freq="M",closed="right")]
vege = ['배추', '무', '미나리', '갓', '쪽파','생강']


url="D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_"
data_list=[]
for date in dates:
    file_name=url+date+'.csv'
    print(file_name)
    temp_data=pd.read_csv(file_name)
    temp_data=temp_data[temp_data['PUM_NM'].isin(vege)] 
    try:
        data_list.append(temp_data)
    except FileNotFoundError as e:
        #국제수산처럼, 파일이 없는 경우.
        continue
    del temp_data
file_name='../files/도매시장/'+'도매시장_2016_2020'+'.csv'
res=pd.concat(data_list)
del data_list
res.to_csv(file_name,index=False)

D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201601.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201602.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201603.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201604.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201605.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201606.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201607.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201608.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201609.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201610.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201611.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201612.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201701.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201702.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201703.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201704.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201705.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201706.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201707.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201708.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201709.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201710.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201711.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201712.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201801.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201802.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201803.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201804.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201805.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201806.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201807.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201808.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201809.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201810.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201811.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201812.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201901.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201902.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201903.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201904.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201905.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201906.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201907.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201908.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201909.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201910.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201911.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_201912.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_202001.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_202002.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_202003.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_202004.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_202005.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_202006.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_202007.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_202008.csv
D:/projects/data/235801_2021 농산물 가격예측 AI 경진대회/public_data/train_AT_TSALET_ALL/AT_TSALET_ALL_202009.csv

ValueError: This sheet is too large! Your sheet size is: 7511314, 15 Max sheet size is: 1048576, 16384

In [10]:
file_name='../files/도매시장/'+'도매시장_2016_2020'+'.csv'
res.to_csv(file_name,index=False)
print(len(res))

7511314

In [1]:
from datetime import datetime
import pandas as pd
import time
import re
import os
import openpyxl
file_name='../files/도매시장/'+'도매시장_2016_2020'+'.csv'
new_df=pd.read_csv(file_name)
new_df.head()

c:\users\desktop\appdata\local\programs\python\python38\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,SALEDATE,WHSAL_NM,CMP_NM,PUM_NM,KIND_NM,DAN_NM,POJ_NM,SIZE_NM,LV_NM,SAN_NM,DANQ,QTY,COST,TOT_QTY,TOT_AMT
0,20160109,부산엄궁도매,부산청과,쪽파,깐쪽파,kg,단,.,보통,제주도 제주시,1.0,10.0,5880.0,10.0,58800.0
1,20160109,부산엄궁도매,부산청과,쪽파,깐쪽파,kg,단,.,보통,제주 북제주군,1.0,50.0,5570.0,50.0,278500.0
2,20160109,부산엄궁도매,부산청과,쪽파,깐쪽파,kg,단,.,보통,제주 북제주군,1.0,50.0,5880.0,50.0,294000.0
3,20160109,부산엄궁도매,부산청과,쪽파,깐쪽파,kg,단,.,보통,제주 북제주군,1.0,40.0,5150.0,40.0,206000.0
4,20160109,부산엄궁도매,부산청과,쪽파,깐쪽파,kg,단,.,보통,제주 북제주군,1.0,20.0,4700.0,20.0,94000.0

In [2]:
file_name='../files/도매시장/'+'more_data1'+'.csv'
more_df1=pd.read_csv(file_name)
more_df1.head()
more_df1.tail()

,PUM_NM,LV_NM,TOT_AMT,SAN_NM,SALEDATE,CMP_NM,DAN_NM,WHSAL_NM,SIZE_NM,COST,POJ_NM,TOT_QTY,QTY,KIND_NM,DANQ
283824,배추,.,720000.0,NaN,20211030,강서청과,kg,서울강서도매,.,3000.0,접,2880.0,240.0,기타배추,12.0
283825,배추,.,108000.0,NaN,20211030,강서청과,kg,서울강서도매,2개,1800.0,접,720.0,60.0,기타배추,12.0
283826,쪽파,.,80000.0,NaN,20211030,강서청과,kg,서울강서도매,1개(내_뿌리),80000.0,상자,10.0,1.0,깐쪽파,10.0
283827,쪽파,.,120000.0,NaN,20211030,강서청과,kg,서울강서도매,13개,40000.0,상자,30.0,3.0,쪽파(일반),10.0
283828,미나리,.,180000.0,NaN,20211030,강서청과,kg,서울강서도매,1개(내_뿌리),12000.0,상자,60.0,15.0,돌미나리,4.0

In [32]:
more_df1

,PUM_NM,LV_NM,TOT_AMT,SAN_NM,SALEDATE,CMP_NM,DAN_NM,WHSAL_NM,SIZE_NM,COST,POJ_NM,TOT_QTY,QTY,KIND_NM,DANQ
283824,배추,.,720000.0,NaN,20211030,강서청과,kg,서울강서도매,.,3000.0,접,2880.0,240.0,기타배추,12.0
283825,배추,.,108000.0,NaN,20211030,강서청과,kg,서울강서도매,2개,1800.0,접,720.0,60.0,기타배추,12.0
283826,쪽파,.,80000.0,NaN,20211030,강서청과,kg,서울강서도매,1개(내_뿌리),80000.0,상자,10.0,1.0,깐쪽파,10.0
283827,쪽파,.,120000.0,NaN,20211030,강서청과,kg,서울강서도매,13개,40000.0,상자,30.0,3.0,쪽파(일반),10.0
283828,미나리,.,180000.0,NaN,20211030,강서청과,kg,서울강서도매,1개(내_뿌리),12000.0,상자,60.0,15.0,돌미나리,4.0

In [3]:
file_name='../files/도매시장/'+'more_data2'+'.csv'
more_df2=pd.read_csv(file_name)
more_df2.head()

,PUM_NM,LV_NM,TOT_AMT,SAN_NM,SALEDATE,CMP_NM,DAN_NM,WHSAL_NM,SIZE_NM,COST,POJ_NM,TOT_QTY,QTY,KIND_NM,DANQ
0,무,.,1456000,제주도 서귀포시,20140103,서울청과,kg,서울가락도매,.,5200.0,.,5040.0,280,기타무,18.0
1,무,.,1540000,제주도 서귀포시,20140103,서울청과,kg,서울가락도매,.,5500.0,.,5040.0,280,기타무,18.0
2,무,.,1596000,제주도 서귀포시,20140103,서울청과,kg,서울가락도매,.,5700.0,.,5040.0,280,기타무,18.0
3,무,.,1400000,제주도 제주시,20140103,서울청과,kg,서울가락도매,.,5000.0,.,5040.0,280,기타무,18.0
4,무,.,1288000,제주도 서귀포시,20140103,서울청과,kg,서울가락도매,.,4600.0,.,5040.0,280,기타무,18.0

In [4]:
#데이터 합치기
new_df2=pd.concat([more_df2,new_df,more_df1])
new_df2.tail()
new_df2.head()

,PUM_NM,LV_NM,TOT_AMT,SAN_NM,SALEDATE,CMP_NM,DAN_NM,WHSAL_NM,SIZE_NM,COST,POJ_NM,TOT_QTY,QTY,KIND_NM,DANQ
0,무,.,1456000.0,제주도 서귀포시,20140103,서울청과,kg,서울가락도매,.,5200.0,.,5040.0,280.0,기타무,18.0
1,무,.,1540000.0,제주도 서귀포시,20140103,서울청과,kg,서울가락도매,.,5500.0,.,5040.0,280.0,기타무,18.0
2,무,.,1596000.0,제주도 서귀포시,20140103,서울청과,kg,서울가락도매,.,5700.0,.,5040.0,280.0,기타무,18.0
3,무,.,1400000.0,제주도 제주시,20140103,서울청과,kg,서울가락도매,.,5000.0,.,5040.0,280.0,기타무,18.0
4,무,.,1288000.0,제주도 서귀포시,20140103,서울청과,kg,서울가락도매,.,4600.0,.,5040.0,280.0,기타무,18.0

In [5]:
#date format 통일시키기
#2020-09-04 -> 20200904
#new_df2["SALEDATE"].str.replace("-","")
new_df2['SALEDATE']=new_df2['SALEDATE'].replace('-','',regex=True)
new_df2[new_df2['SALEDATE']=="2020-09-04"]

Empty DataFrame
Columns: [PUM_NM, LV_NM, TOT_AMT, SAN_NM, SALEDATE, CMP_NM, DAN_NM, WHSAL_NM, SIZE_NM, COST, POJ_NM, TOT_QTY, QTY, KIND_NM, DANQ]
Index: []

In [6]:
#품목별 분류
vege = ['배추', '무', '미나리', '갓', '쪽파','생강']
for ve in vege:
    file_name='../files/전처리/'
    file_name=file_name+ve+'.csv'
    print(len(new_df2[new_df2["PUM_NM"]==ve]))
    new_df2[new_df2["PUM_NM"]==ve].to_csv(file_name,index=False)

2392573
1591239
1226285
397045
2458419
492253

In [51]:
new_df[new_df['SALEDATE']=="2020-09-04"]

,SALEDATE,WHSAL_NM,CMP_NM,PUM_NM,KIND_NM,DAN_NM,POJ_NM,SIZE_NM,LV_NM,SAN_NM,DANQ,QTY,COST,TOT_QTY,TOT_AMT
7398889,2020-09-04,서울강서도매,강서청과,배추,기타배추,kg,접,.,.,서울 송파구,12.0,-290.0,6500.0,-3480.0,-1885000.0
7398890,2020-09-04,서울강서도매,강서청과,배추,기타배추,kg,접,2개,.,서울 송파구,12.0,-73.0,3900.0,-876.0,-284700.0
7398891,2020-09-04,서울강서도매,강서청과,배추,기타배추,kg,접,2개,.,서울 송파구,12.0,70.0,3900.0,840.0,273000.0
7398892,2020-09-04,서울강서도매,강서청과,배추,기타배추,kg,접,.,.,서울 송파구,12.0,282.0,6500.0,3384.0,1833000.0
7398893,2020-09-04,서울강서도매,강서청과,배추,기타배추,kg,접,2개,.,서울 송파구,12.0,73.0,3900.0,876.0,284700.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7401905,2020-09-04,익산도매시장,익산원협(공),무,기타무,kg,상자,NaN,상,전라북도 진안군,20.0,7.0,6600.0,140.0,46200.0
7401906,2020-09-04,익산도매시장,익산원협(공),무,기타무,kg,상자,12개,특,전라북도 진안군,20.0,18.0,9200.0,360.0,165600.0
7401907,2020-09-04,익산도매시장,익산원협(공),무,무말랭이,kg,상자,NaN,특,서울 송파구,1.0,10.0,10077.0,10.0,100770.0
7401908,2020-09-04,익산도매시장,익산원협(공),무,무말랭이,kg,상자,NaN,특,서울 송파구,1.0,2.0,10077.0,2.0,20154.0
7401909,2020-09-04,익산도매시장,익산원협(공),무,기타무,kg,상자,10개,특,전라북도 진안군,20.0,29.0,12500.0,580.0,362500.0

In [7]:
new_df2['SALEDATE'] = pd.to_datetime(new_df2['SALEDATE'], format='%Y%m%d')
new_df2.sort_values(by='SALEDATE')

,PUM_NM,LV_NM,TOT_AMT,SAN_NM,SALEDATE,CMP_NM,DAN_NM,WHSAL_NM,SIZE_NM,COST,POJ_NM,TOT_QTY,QTY,KIND_NM,DANQ
0,무,.,1456000.0,제주도 서귀포시,2014-01-03,서울청과,kg,서울가락도매,.,5200.0,.,5040.0,280.0,기타무,18.0
1029,쪽파,특,310000.0,충청남도 예산군,2014-01-03,한국청과,kg,서울가락도매,.,31000.0,상자,100.0,10.0,쪽파(일반),10.0
1028,쪽파,특,319000.0,충청남도 예산군,2014-01-03,한국청과,kg,서울가락도매,.,29000.0,상자,110.0,11.0,쪽파(일반),10.0
1027,쪽파,특,363000.0,충청남도 예산군,2014-01-03,한국청과,kg,서울가락도매,.,33000.0,상자,110.0,11.0,쪽파(일반),10.0
1026,쪽파,특,560000.0,충청남도 예산군,2014-01-03,한국청과,kg,서울가락도매,.,35000.0,상자,160.0,16.0,쪽파(일반),10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278600,생강,특,105000.0,서울 송파구,2021-10-30,대인농산,kg,인천구월도매,.,21000.0,상자,50.0,5.0,생강(일반),10.0
278599,생강,특,3000.0,서울 송파구,2021-10-30,대인농산,kg,인천구월도매,.,3000.0,상자,10.0,1.0,생강(일반),10.0
278598,생강,특,76000.0,서울 송파구,2021-10-30,대인농산,kg,인천구월도매,.,19000.0,상자,40.0,4.0,생강(일반),10.0
278596,생강,특,45000.0,서울 송파구,2021-10-30,대인농산,kg,인천구월도매,.,15000.0,상자,30.0,3.0,생강(일반),10.0
283828,미나리,.,180000.0,NaN,2021-10-30,강서청과,kg,서울강서도매,1개(내_뿌리),12000.0,상자,60.0,15.0,돌미나리,4.0

In [12]:
print(len(new_df2))
new_df2.head()
#2014 01.03~ 2021-10-30
#총 8557814

8557814

,PUM_NM,LV_NM,TOT_AMT,SAN_NM,SALEDATE,CMP_NM,DAN_NM,WHSAL_NM,SIZE_NM,COST,POJ_NM,TOT_QTY,QTY,KIND_NM,DANQ
0,무,.,1456000.0,제주도 서귀포시,20140103,서울청과,kg,서울가락도매,.,5200.0,.,5040.0,280.0,기타무,18.0
1,무,.,1540000.0,제주도 서귀포시,20140103,서울청과,kg,서울가락도매,.,5500.0,.,5040.0,280.0,기타무,18.0
2,무,.,1596000.0,제주도 서귀포시,20140103,서울청과,kg,서울가락도매,.,5700.0,.,5040.0,280.0,기타무,18.0
3,무,.,1400000.0,제주도 제주시,20140103,서울청과,kg,서울가락도매,.,5000.0,.,5040.0,280.0,기타무,18.0
4,무,.,1288000.0,제주도 서귀포시,20140103,서울청과,kg,서울가락도매,.,4600.0,.,5040.0,280.0,기타무,18.0

In [11]:
print(len(res))
res.head()

7511314

,SALEDATE,WHSAL_NM,CMP_NM,PUM_NM,KIND_NM,DAN_NM,POJ_NM,SIZE_NM,LV_NM,SAN_NM,DANQ,QTY,COST,TOT_QTY,TOT_AMT
44,20160109,부산엄궁도매,부산청과,쪽파,깐쪽파,kg,단,.,보통,제주도 제주시,1.0,10.0,5880.0,10.0,58800.0
151,20160109,부산엄궁도매,부산청과,쪽파,깐쪽파,kg,단,.,보통,제주 북제주군,1.0,50.0,5570.0,50.0,278500.0
152,20160109,부산엄궁도매,부산청과,쪽파,깐쪽파,kg,단,.,보통,제주 북제주군,1.0,50.0,5880.0,50.0,294000.0
153,20160109,부산엄궁도매,부산청과,쪽파,깐쪽파,kg,단,.,보통,제주 북제주군,1.0,40.0,5150.0,40.0,206000.0
154,20160109,부산엄궁도매,부산청과,쪽파,깐쪽파,kg,단,.,보통,제주 북제주군,1.0,20.0,4700.0,20.0,94000.0

In [12]:
new_df=pd.read_csv(file_name)
new_df.head()

c:\users\desktop\appdata\local\programs\python\python38\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,SALEDATE,WHSAL_NM,CMP_NM,PUM_NM,KIND_NM,DAN_NM,POJ_NM,SIZE_NM,LV_NM,SAN_NM,DANQ,QTY,COST,TOT_QTY,TOT_AMT
0,20160109,부산엄궁도매,부산청과,쪽파,깐쪽파,kg,단,.,보통,제주도 제주시,1.0,10.0,5880.0,10.0,58800.0
1,20160109,부산엄궁도매,부산청과,쪽파,깐쪽파,kg,단,.,보통,제주 북제주군,1.0,50.0,5570.0,50.0,278500.0
2,20160109,부산엄궁도매,부산청과,쪽파,깐쪽파,kg,단,.,보통,제주 북제주군,1.0,50.0,5880.0,50.0,294000.0
3,20160109,부산엄궁도매,부산청과,쪽파,깐쪽파,kg,단,.,보통,제주 북제주군,1.0,40.0,5150.0,40.0,206000.0
4,20160109,부산엄궁도매,부산청과,쪽파,깐쪽파,kg,단,.,보통,제주 북제주군,1.0,20.0,4700.0,20.0,94000.0

In [15]:
len(new_df)
del new_df

NameError: name 'new_df' is not defined

In [10]:
data["PUM_NM"].unique()

array(['감귤', '만감', '오이', '쪽파', '브로코리(녹색꽃양배추)', '적채', '콜라비(순무양배추)', '고구마',
       '감자', '대파', '호박', '딸기', '칼리플라워(꽃양배추)', '비트(붉은사탕무우)', '배추', '기타',
       '부추', '무', '미나리', '양파', '우엉', '사과', '시금치', '쑥', '양상추', '상추',
       '피망(단고추)', '가지', '오렌지', '레몬', '방아', '봄동배추', '열무', '참나물', '머위대',
       '동초', '냉이', '토마토', '풋고추', '홍고추', '돗나물', '로메인', '청경채', '치커리', '근대',
       '케일', '새송이', '팽이버섯', '만가닥', '느타리버섯', '생강', '마늘', '방울토마토', '꽈리고추',
       '수박', '단감', '양송이', '표고버섯', '곶감', '쑥갓', '파세리(향미나리)', '셀러리(양미나리)',
       '깻잎', '겨자채', '마', '연근', '도라지', '미역', '우뭇가사리', '취나물', '비타민', '새싹',
       '파프리카', '당근', '양배추', '고수', '얼갈이배추', '유채', '달래', '고비', '고사리',
       '조미제품', '곡물제조', '고구마순', '토란대', '갓', '무순', '전분 및 사료제조', '콩나물',
       '숙주나물', '계피', '목이', '참깨', '바나나', '파인애플', '유지', '대추', '절임식품',
       '조미가공', '다시마', '파래', '어묵_어분_어비', '차', '황기', '과루인(하늘타리)', '포도',
       '아욱', '밤', '떫은감', '배', '겨자', '참당귀', '쌈추', '방울양배추(스프로스)', '속새',
       '건고추', '은행', '무청', '감초', '참다래(키위)', '체리', '오크라', '토란', '메론', '땅콩',
       '춘채', '기타식품', '시레기', '더덕', '방풍나물', '석류', '콩', '강낭콩', '젓갈', '자몽',
       '꼬시래기', '야생화', '수삼', '들깨', '무종자', '피망잎', '양하', '솔잎', '울금', '망고',
       '초석잠', '여주', '선인장열매', '씀바귀', '식용허브', '아스파라가스', '실파', '돌나물', '블루베리',
       '보리순', '유자', '알타리무', '야콘', '질경이', '조란', '모자반', '순무', '말', '고추잎',
       '허브', '알로애', '비름', '동부', '알파파싹', '신선초', '우엉대', '민들레', '삼채', '체리모야',
       '겨자잎', '보리', '두릅', '인삼', '애느타리버섯', '근괴류', '아보카도', '호두', '호박씨',
       '완두', '고추씨', '금감', '팥', '용과', '동충하초', '레드쉬', '다래', '삼엽채', '녹두',
       '수수', '곤드레나물', '방풍', '모과', '가랏', '금강초', '메밀', '크레송(고추무냉이)', '고들빼기',
       '파파야', '홍화씨', '곤달비', '복숭아', '독활', '듀리안', '코코넛', '노루궁뎅이버섯', '묵나물',
       '빈스', '김', '메밀순', '구약', '꿀벌', '멸치', '옥수수', '통조림', '상황버섯', '카이란',
       '조', '람부탄', '가죽나물', '박', '고라비', '아몬드', '산약', '오가피', '석이', '버찌',
       '무늬목', '교나', '잣', '해바라기씨', '호박잎', '참외', '산마늘', '국화(기타)', '자연산송이',
       '무화과', '죽순', '도토리', '알로에', '아주까리', '천궁', '차류', '찹쌀', '패션푸룻', '원추리',
       '참죽나무순', '리치', '건제품', '아스파라거스', '종자', '영지버섯', '갈근', '강황', '피마자잎',
       '자두', '육가공품'], dtype=object)

In [13]:
options = ['배추', '무', '갓','미나리','쪽파','생강','마늘']

# selecting rows based on condition
select_data = data[data['PUM_NM'].isin(options)]

print(len(select_data))
select_data.head()
#이제 파일들 읽어서 저장하는걸로 바꿔야함.

112969

,SALEDATE,WHSAL_NM,CMP_NM,PUM_NM,KIND_NM,DAN_NM,POJ_NM,SIZE_NM,LV_NM,SAN_NM,DANQ,QTY,COST,TOT_QTY,TOT_AMT
44,20160109,부산엄궁도매,부산청과,쪽파,깐쪽파,kg,단,.,보통,제주도 제주시,1.0,10,5880.0,10.0,58800
151,20160109,부산엄궁도매,부산청과,쪽파,깐쪽파,kg,단,.,보통,제주 북제주군,1.0,50,5570.0,50.0,278500
152,20160109,부산엄궁도매,부산청과,쪽파,깐쪽파,kg,단,.,보통,제주 북제주군,1.0,50,5880.0,50.0,294000
153,20160109,부산엄궁도매,부산청과,쪽파,깐쪽파,kg,단,.,보통,제주 북제주군,1.0,40,5150.0,40.0,206000
154,20160109,부산엄궁도매,부산청과,쪽파,깐쪽파,kg,단,.,보통,제주 북제주군,1.0,20,4700.0,20.0,94000

In [15]:
select_data.isna().sum()

SALEDATE       0
WHSAL_NM       0
CMP_NM         0
PUM_NM         0
KIND_NM        0
DAN_NM         0
POJ_NM       140
SIZE_NM     2040
LV_NM          0
SAN_NM      2757
DANQ           0
QTY            0
COST           0
TOT_QTY        0
TOT_AMT        0
dtype: int64

In [5]:
data[data['PUM_NM']=='배추']

,SALEDATE,WHSAL_NM,CMP_NM,PUM_NM,KIND_NM,DAN_NM,POJ_NM,SIZE_NM,LV_NM,SAN_NM,DANQ,QTY,COST,TOT_QTY,TOT_AMT
165,20160109,부산엄궁도매,부산청과,배추,쌈배추,kg,상자,.,보통,광주 북구,10.0,25,6110.0,250.0,152750
262,20160109,부산엄궁도매,부산청과,배추,쌈배추,kg,상자,.,보통,광주 북구,10.0,25,6200.0,250.0,155000
263,20160109,부산엄궁도매,부산청과,배추,쌈배추,kg,상자,.,보통,광주 북구,10.0,25,6200.0,250.0,155000
325,20160109,부산엄궁도매,부산청과,배추,기타배추,kg,단,.,보통,부산 중구,4.0,100,2500.0,400.0,250000
434,20160109,부산엄궁도매,부산청과,배추,기타배추,kg,그물망,.,보통,전라남도 해남군,15.0,700,4000.0,10500.0,2800000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2700717,20160130,서울강서도매,강서청과,배추,기타배추,kg,접,.,.,경기 안성시,12.0,730,6300.0,8760.0,4599000
2700718,20160130,서울강서도매,강서청과,배추,기타배추,kg,접,.,.,경기 안성시,12.0,190,3800.0,2280.0,722000
2700719,20160130,서울강서도매,강서청과,배추,기타배추,kg,접,.,.,경기 안성시,12.0,690,6500.0,8280.0,4485000
2700720,20160130,서울강서도매,강서청과,배추,기타배추,kg,접,.,.,경기 안성시,12.0,100,3900.0,1200.0,390000
2700721,20160130,서울강서도매,강서청과,배추,기타배추,kg,접,.,.,경기 안성시,12.0,170,3300.0,2040.0,561000